spring.application.name=backend

#spring.config.import=env:DATABASE_CONFIG


#server.servlet.context-path=/api
spring.datasource.url= ${POSTGRES_URI}
spring.datasource.username= ${POSTGRES_USERNAME}
spring.datasource.password = ${POSTGRES_PASSWORD}
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect


#mailing service
spring.mail.host=smtp.gmail.com
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.auth.app=Grizzly
jwt.auth.secret_key = ${JWT_SECRET}
jwt.auth.expires_in = 3600 

# Google SignIn
spring.security.oauth2.client.registration.google.client-id= ${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri= ${GOOGLE_URI}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=${GOOGLE_AUTH_URI}
spring.security.oauth2.client.provider.google.token-uri=${GOOGLE_TOKEN_URI}
spring.security.oauth2.client.provider.google.user-info-uri= ${USER_INFO_URI}
